export const LOAD_POKEMON = 'LOAD_POKEMON';
export const LOAD_ABILITIES = 'LOAD_ABILITIES';
export const LOAD_MOVES = 'LOAD_MOVES';
export const LOAD_ITEMS = 'LOAD_ITEMS';
export const SELECT_POKEMON = 'SELECT_POKEMON';